The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/janderson/PycharmProjects/concrete/src/concrete_project/urls.py", line 40, in <module>
    url(r'^service_group/', include('service_group.urls')),
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/janderson/PycharmProjects/concrete/src/service_group/urls.py", line 2, in <module>
    from service_group.views import ConcreteCreate, StepsCreate, FoundationCreate, \
  File "/Users/janderson/PycharmProjects/concrete/src/service_group/views.py", line 10, in <module>
    from service_group.forms import StandardConcreteForm, DecorativeConcreteForm, StepsForm, FoundationForm, \
  File "/Users/janderson/PycharmProjects/concrete/src/service_group/forms.py", line 19, in <module>
    class StandardConcreteForm(forms.Form):
  File "/Users/janderson/PycharmProjects/concrete/src/service_group/forms.py", line 27, in StandardConcreteForm
    initial=get_one_object('Concrete Driveway Mix'))
  File "/Users/janderson/PycharmProjects/concrete/src/service_group/forms.py", line 15, in get_one_object
    my_obj = Service.objects.get(description=service_name)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: service_service
(env) Jeffreys-MacBook-Pro:src janderson$ python manage.py makemigrations
Traceback (most recent call last):
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/janderson/PycharmProjects/concrete/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: service_service
